permits/urls.py
from django.contrib import admin
from django.urls import path
from siteinfo import  views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.MainView.as_view(), name='home'),
    path('thank-you/', views.ThankYouView.as_view(), name='thank-you'),
    path('<slug:slug>/', views.DetailView.as_view(), name='alpha'),
]

permits/models.py
from django.db import models

class Service(models.Model):
    title = models.CharField(max_length=200)
    detail = models.TextField()

class Description(models.Model):
    detail = models.TextField()

    def save(self, *args, **kwargs):
        if not self.pk and Description.objects.exists():
            raise ValidationError('There can only be one')
        return super(Description, self).save(*args,**kwargs)

siteinfo/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.core.exceptions import ValidationError
from django.core import mail
from django.core.mail.backends.smtp import EmailBackend
from django.core.mail import EmailMessage
from django.core.mail import send_mail

class ASection(models.Model):
    title = models.CharField(max_length=250)
    summary = models.TextField()

    def save(self, *args, **kwargs):
        if not self.pk and ASection.objects.exists():
            raise ValidationError('There can only be one')
        return super().save(*args,**kwargs)

        
    


class Alpha(models.Model):
    section = models.ForeignKey(ASection, on_delete=models.CASCADE)    
    title = models.CharField(max_length=500)
    summary = models.TextField()
    text = models.TextField()
    button_prompt = models.CharField(max_length=250)    
    order = models.IntegerField()

    slug = models.SlugField(blank=True,null=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args,**kwargs)

    class Meta:
        ordering = ['order']


class BSection(models.Model):
    title = models.CharField(max_length=250)
    summary = models.TextField()

    def save(self, *args, **kwargs):
        if not self.pk and BSection.objects.exists():
            raise ValidationError('There can only be one')
        return super().save(*args,**kwargs)
    
    
    
class Bravo(models.Model):
    section = models.ForeignKey(BSection, on_delete=models.CASCADE)
    title = models.CharField(max_length=500)
    summary = models.TextField()
    order = models.IntegerField()

    class Meta:
        ordering = ['order']

        
class Landing(models.Model):
    title =  models.CharField(max_length=250)
    text = models.TextField()
    message = models.TextField()
    button_prompt = models.CharField(max_length=250)

    def save(self, *args, **kwargs):
        if not self.pk and Landing.objects.exists():
            raise ValidationError('There can only be one')
        return super(Landing, self).save(*args,**kwargs)


class Contact(models.Model):
    title = models.CharField(max_length=250)
    summary = models.TextField()
    address = models.CharField(max_length=250)
    city = models.CharField(max_length=100)
    state =  models.CharField(max_length=100)
    zipcode = models.CharField(max_length=5)

    email = models.EmailField()
    phone = models.CharField(max_length=10)

    def format_address(self,*args,**kwargs):
        f = self.address + ',\n' + self.city + ', ' + self.state + ' ' + self.zipcode
        return f

    def format_phone(self,*args,**kwargs):
        p = self.phone

        f = '('+p[:3]+') ' + p[3:6] + ' ' + p[6:]
        return f

    def save(self, *args, **kwargs):
        if not self.pk and Contact.objects.exists():
            raise ValidationError('There can only be one')
        return super(Contact, self).save(*args,**kwargs)
    
    def send_message(self,args):
        subject = 'New Inquiry on AcePermits'

        content = ""
        for (k,v) in args:
            content = content + k + ": " + v + "\n\n"

        with mail.get_connection() as connection:
            msg = EmailMessage(subject,
                               content,
                               self.email,
                               [self.email,],
                               connection=connection
            )
            msg.send()

siteinfo/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import ValidationError

CHOICES = [
    ("Feature","Feature"),
    ("TV","TV"),
    ("Movie","Movie"),
    ("Commercial","Commercial"),
    ("Music Video","Music Video"),
    ("Student Film","Student Film"),
    ("Live Performance","Live Performance"),
    ("Other","Other"),
]

class ContactForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()    
    company = forms.CharField()
    email = forms.EmailField()
    phone = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)
    choices = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect)

    def clean_first_name(self):
        data = self.cleaned_data['first_name']
        if not data:
            raise ValidationError(_('Please complete this field.'))
        return data

    def clean_last_name(self):
        data = self.cleaned_data['last_name']
        if not data:
            raise ValidationError(_('Please complete this field.'))
        return data

    def clean_company(self):
        data = self.cleaned_data['company']
        #if not data:
        #    raise ValidationError(_('Please complete this field.'))
        return data

    def clean_email(self):
        data = self.cleaned_data['email']
        if not data:
            raise ValidationError(_('Please complete this field.'))
        return data

    def clean_phone(self):
        data = self.cleaned_data['phone']
        if not data:
            raise ValidationError(_('Please complete this field.'))
        return data

    def clean_message(self):
        data =self.cleaned_data['message']
        if not data:
            raise ValidationError(_('Please enter your message here.'))
        return data

    def clean_choices(self):
        data = self.cleaned_data['choices']
        if not data:
            raise ValidationError(_('Please select a choice.'))
        return data

permits/views.py
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView

class MainView(TemplateView):
    template_name = 'siteinfo/main.html'

    

siteinfo/views.py
from django.shortcuts import redirect
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView
from .models import ASection, Alpha, BSection, Bravo, Landing, Contact
from .forms import ContactForm

class MainView(FormView):
    template_name = 'siteinfo/main.html'
    form_class = ContactForm
    contact = Contact.objects.first()

    def get_context_data(self,*args,**kwargs):
        context = super().get_context_data(*args,**kwargs)
        context['landing'] = Landing.objects.first()
        context['alpha'] = ASection.objects.first()
        context['bravo'] = BSection.objects.first()
        context['contact'] = self.contact

        return context

    def form_valid(self,form):
        args = [
            ('first_name',form.cleaned_data['first_name']),
            ('last_name', form.cleaned_data['last_name']),
            ('company', form.cleaned_data['company']),
            ('email', form.cleaned_data['email']),
            ('phone', form.cleaned_data['phone']),
            ('choice', form.cleaned_data['choices']),
            ('message', form.cleaned_data['message']),
        ]
        

        self.contact.send_message(args)
        return redirect('/thank-you/')
        

class ThankYouView(TemplateView):
    template_name = 'siteinfo/thankyou.html'
    contact = Contact.objects.first()
    
    def get_context_data(self,*args,**kwargs):
        context = super().get_context_data(*args,**kwargs)
        context['landing'] = Landing.objects.first()
        context['alpha'] = ASection.objects.first()
        context['bravo'] = BSection.objects.first()
        context['contact'] = self.contact

        return context
    
class DetailView(TemplateView):
    template_name  = 'siteinfo/detail.html'
    contact = Contact.objects.first()
    
    def get_context_data(self, *args, **kwargs):
        slug = kwargs.get('slug')
        context = super().get_context_data(*args, **kwargs)
        context['landing'] = Landing.objects.first()
        context['alpha'] = ASection.objects.first()
        context['bravo'] = BSection.objects.first()
        context['contact'] = self.contact
        context['obj'] = Alpha.objects.get(slug=slug)
        return context

siteinfo/templates/siteinfo/detail.html
<!DOCTYPE HTML>
<!--
    Hyperspace by HTML5 UP
    html5up.net | @ajlkn
    Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
  -->
<html>
  {% load static %}
  <head>
    <title></title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="{% static 'siteinfo/assets/css/main.css' %}">
    <noscript><link rel="stylesheet" href="{% static 'siteinfo/assests/css/noscript.css' %}"></noscript>
  </head>
  
  
  <body class="is-preload">
    
    <!-- Header -->
    <header id="header" class="">
      <a href="/" class="title">Home</a>
      <nav>
	{% comment %}
	<ul>
	  <li><a href="/">Home</a></li>
	  <li><a href="generic.html" class="active">Generic</a></li>
	  <li><a href="elements.html">Elements</a></li>
	</ul>
	{% endcomment %}
      </nav>
    </header>
    
    <!-- Wrapper -->
    <div id="wrapper">
      
      <!-- Main -->
      <section id="main" class="wrapper style5">
	<div class="inner">
	  <h1 class="major">{{ obj.title }}</h1>
	  <p>{{ obj.text|linebreaks }}</p>
	</div>
      </section>
      
    </div>
    
    <!-- Footer -->
    <footer id="footer" class="wrapper alt style5">
      <div class="inner">
	<ul class="menu">
	  <li>&copy; {{ landing.title }}. All rights reserved.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
	</ul>
      </div>
    </footer>
    
    <!-- Scripts -->
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/js/jquery.scrollex.min.js"></script>
    <script src="assets/js/jquery.scrolly.min.js"></script>
    <script src="assets/js/browser.min.js"></script>
    <script src="assets/js/breakpoints.min.js"></script>
    <script src="assets/js/util.js"></script>
    <script src="assets/js/main.js"></script>
    
  </body>
</html>

siteinfo/templates/siteinfo/main.html
<html>
  {% load static %}
  <head>
    <title></title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="{% static 'siteinfo/assets/css/main.css' %}">
    <noscript><link rel="stylesheet" href="{% static 'siteinfo/assests/css/noscript.css' %}"></noscript>
  </head>



  <body class="style5">
    
    <!-- Sidebar -->
    {% comment %}
    <section id="sidebar" class="style5">
      <div class="inner style5">
	<nav>
	  <ul>
	    <li><a href="#intro">Welcome</a></li>
	    <li><a href="#one">{{ alpha.title }}</a></li>
	    <li><a href="#two">{{ bravo.title }}</a></li>
	    <li><a href="#three">{{ contact.title }}</a></li>
	  </ul>
	</nav>
      </div>
    </section>
    {% endcomment %}
    
    <!-- Wrapper -->
    <div id="wrapper">
      
      <!-- Intro -->
      <section id="intro" class="wrapper fullscreen style5">
	<div class="inner">
	  <center>
	    <img src="/static/siteinfo/images/logo.png" class="logo">
	    <h1>{{ landing.title|safe }}</h1>
	    <div class="landing">
	      <p>{{ landing.text|safe }}</p>
	      <a href="#two" class="button scrolly">{{ landing.button_prompt }}</a>
	    </div>
	    <ul class="actions">
	      <li>
	      </li>
	    </ul>
	  </center>
	</div>
      </section>



      {% comment %}
      <!-- One -->
      <section id="one" class="wrapper spotlights style5">

	{% for a in alpha.alpha_set.all %}
	<section class="dinner">
	  <a href="#" class="image"><img src="static/siteinfo/images/empirestate.jpg" alt=""p /></a>
	  <div class="content">
	    <div class="inner dinner">
	      <h2>{{ a.title }}</h2>
	      <p>{{ a.summary|linebreaks }}</p>
	      <ul class="actions">
		<li><a href="{% url 'alpha' a.slug %}" class="button">Learn more</a></li>
	      </ul>
	    </div>
	  </div>
	</section>
	{% endfor %}
      </section>
      {% endcomment %}

      <!--Two -->
      <center>
	<section id="two" class="wrapper fade-up style5">
	  <div class="inner dinner karm">
	    <p>{{landing.message|safe}}</p>
	  </div>
	</section>
      </center>
	  

      {% comment %}
      <!-- Two -->
      <section id="two" class="wrapper fade-up style5">
	<div class="inner dinner">
	  <h2>{{ bravo.title }}</h2>
	  <p>{{ bravo.summary|linebreaks }}</p>
	  <div class="features">
	    {% for b in bravo.bravo_set.all %}
	    <section>
	      <span class="icon solid major fa-check"></span>
	      <h3>{{ b.title }}</h3>
	      <p>{{ b.summary|linebreaks }}</p>
	    </section>
	    {% endfor %}
	  </div>
	    <ul class="actions">
	      <li><a href="generic.html" class="button">Learn more</a></li>
	    </ul>
	</div>
      </section>
      {% endcomment %}
      
      <!-- Three -->
      <section id="three" class="wrapper fade-up style5">
	<div class="inner dinner">
	  <h2>{{ contact.title }}</h2>
	  <p>{{ contact.summary|linebreaks }}</p>
	  <div class="split style1">
	    <section>
	      <form method="post" action="">
		{% csrf_token %}

		<div class="fields">
		  <div class="field third">
		    <label for="first_name">First Name</label>
		    <input type="text" name="first_name" id="first_name" />
		  </div>
		  <div class="field third">
		    <label for="last_name">Last Name</label>
		    <input type="text" name="last_name" id="last_name" />
		  </div>
		  <div class="field third">
		    <label for="company">Production Company</label>
		    <input type="text" name="company" id="company" />
		  </div>
		  <div class="field half">
		    <label for="phone">Phone Number</label>
		    <input type="text" name="phone" id="phone" />
		  </div>
		  <div class="field half">
		    <label for="email">Email</label>
		    <input type="text" name="email" id="email" />
		  </div>

		  {% for choice,display in form.fields.choices.choices %}
		  <div class="field quarter">
		    <input type="radio" name="choices" id={{choice}} value={{choice}}>
		    <label for={{choice}}>{{choice}}</label>
		  </div>
		  {% endfor %}

		  <div class="field">
		    <label for="message">Details about your location including location address</label>
		    <textarea name="message" id="message" rows="5"></textarea>
		  </div>
		</div>
		<ul class="actions">
		  <li><input type="submit" value="Send Message"></li>
		</ul>
	      </form>
	    </section>


	    {% comment %}
	    <section>
	      <ul class="contact">
		<li>
		  <h3>Address</h3>
		  <span>{{ contact.address }}<br />
		    {{ contact.city }}, {{ contact.state }} {{ contact.zipcode }}<br />
		    USA</span>
		</li>
		<li>
		  <h3>Email</h3>
		  <a href="">{{ contact.email }}</a>
		</li>
		<li>
		  <h3>Phone</h3>
		  <span>{{ contact.format_phone }}</span>
		</li>
		<li>
		  <h3>Social</h3>
		  <ul class="icons">
		    <li><a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
		    <li><a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
		    <li><a href="#" class="icon brands fa-github"><span class="label">GitHub</span></a></li>
		    <li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
		    <li><a href="#" class="icon brands fa-linkedin-in"><span class="label">LinkedIn</span></a></li>
		  </ul>
		</li>
	      </ul>
	    </section>
	    {% endcomment %}
	    
	  </div>
	</div>
      </section>
      
    </div>
    
    <!-- Footer -->
    <footer id="footer" class="wrapper style5">
      <div class="inner dinner">
	<ul class="menu">
	  <li>&copy; {{ landing.title }} All rights reserved.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
	</ul>
      </div>
    </footer>
    
    <!-- Scripts -->
    <script src="{% static 'siteinfo/assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'siteinfo/assets/js/jquery.scrollex.min.js' %}"></script>
    <script src="{% static 'siteinfo/assets/js/jquery.scrolly.min.js' %}"></script>
    <script src="{% static 'siteinfo/assets/js/browser.min.js' %}"></script>
    <script src="{% static 'siteinfo/assets/js/breakpoints.min.js' %}"></script>
    <script src="{% static 'siteinfo/assets/js/util.js' %}"></script>
    <script src="{% static 'siteinfo/assets/js/main.js' %}"></script>
    
  </body>
</html>

siteinfo/templates/siteinfo/thankyou.html
<!DOCTYPE HTML>
<!--
    Hyperspace by HTML5 UP
    html5up.net | @ajlkn
    Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
  -->
<html>
  {% load static %}
  <head>
    <title></title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="{% static 'siteinfo/assets/css/main.css' %}">
    <noscript><link rel="stylesheet" href="{% static 'siteinfo/assests/css/noscript.css' %}"></noscript>
  </head>
  
  
  <body class="is-preload">
    
    <!-- Header -->
    <header id="header">
      <a href="/" class="title">Home</a>
      <nav>
	<ul>
	  <li><a href="index.html">Home</a></li>
	  <li><a href="generic.html" class="active">Generic</a></li>
	  <li><a href="elements.html">Elements</a></li>
	</ul>
      </nav>
    </header>
    
    <!-- Wrapper -->
    <div id="wrapper">
      
      <!-- Main -->
      <section id="main" class="wrapper">
	<div class="inner">
	  <h1 class="major">Thank You</h1>
	  <p>You message has been received, please keep your eyes open for our response.</p>
	</div>
      </section>
      
    </div>

    {% comment  %}
    <!-- Footer -->
    <footer id="footer" class="wrapper alt">
      <div class="inner">
	<ul class="menu">
	  <li>&copy; {{ landing.title }} All rights reserved.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
	</ul>
      </div>
    </footer>
    {% endcomment %}
    
    <!-- Scripts -->
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/js/jquery.scrollex.min.js"></script>
    <script src="assets/js/jquery.scrolly.min.js"></script>
    <script src="assets/js/browser.min.js"></script>
    <script src="assets/js/breakpoints.min.js"></script>
    <script src="assets/js/util.js"></script>
    <script src="assets/js/main.js"></script>
    
  </body>
</html>